### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by CarrieWang0319** [ddlee-cn/MuLUT#12]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "4_test_lut.py", line 340, in <module>
    etr.run()
  File "4_test_lut.py", line 259, in run
    psnr_ssim_s = pool.map(self._worker, list(range(len(self.files))))
  File "E:\python\anaconda\envs\yolov5\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "E:\python\anaconda\envs\yolov5\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

**Comment by ddlee-cn** [comment]
Please provide more error details inside multi-threading or simply disable it and change to for-loop.
